version: '3.5'

services:
  db_aut:
    container_name: todolist-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:14-alpine3.19